version: '3.2'
services:
    builder:
        image: jenkins-ci/builder:1.0
        build:
            context: ${PWD}
            dockerfile: DockerfileBuilder
            args:
                AGENT_PASSWORD: ${AGENT_PASSWORD}
                AGENT_USER: ${AGENT_USER}
        command: bash -c '/usr/sbin/sshd ; tail -f /dev/null'
    server:
        image: jenkins-ci/server:1.0
        build:
            context: ${PWD}
            dockerfile: DockerfileServer
        depends_on:
            - "builder"
        environment:
            - CASC_JENKINS_CONFIG=/var/jenkins/casc_configs/jenkins.yml
            - AGENT_PASSWORD=${AGENT_PASSWORD}
            - AGENT_USER=${AGENT_USER}
        ports:
            - 8080:8080
        volumes:
            - ./data:/var/jenkins/data
            - ./casc_configs:/var/jenkins/casc_configs
